#! /usr/bin/python

from __future__ import print_function
import copy
import random

time_limit = 20 # the number of time steps to simulate
size = 9 # the width and height of the simulation area in blocks
stencil = {(u, v) for u in range(-1, 2) for v in range(-1, 2) if (u, v) != (0, 0)}

def get_neighbors(point):
	result = set()
	for offset in stencil:
		x = point[0] + offset[0]
		if x >= 0 and x < size:
			y = point[1] + offset[1]
			if y >= 0 and y < size:
				result |= {(x, y)}
	return result

zones = [' ', 'I', 'R', 'C'] # empty, industrial, residential, commercial

city = [[random.choice(zones) for y in range(size)] for x in range(size)]
print(city)
for step in range(time_limit):
	new_city = copy.deepcopy(city)
	for x in range(size):
		for y in range(size):
			empty_cell_total = 0
			for offset in stencil:
				if x + offset[0] >= 0 and y + offset[1] >= 0:
					if x + offset[0] < size and y + offset[1] < size:
						if new_city[x + offset[0]][y + offset[1]] == zones[0]:
							empty_cell_total += 1
			if new_city[x][y] != zones[0] and empty_cell_total == 0:
				new_city[x][y] == zones[0]
			if new_city[x][y] == zones[0] and empty_cell_total <= 2:
				new_city[x][y] == zones[1]
			if new_city[x][y] == zones[1] and empty_cell_total >= 3:
				new_city[x][y] == zones[2]
			if new_city[x][y] == zones[2] and empty_cell_total >= 4:
				new_city[x][y] == zones[3]

	print('Step {step}:'.format(step = step))
	for y in reversed(range(size)):
		print('  ', end = '')
		for x in range(size):
			print(new_city[x][y], end = '')
		print()
	print()
	city = new_city
